services:
  technitium:
    image: technitium/dns-server:latest
    container_name: technitium
    hostname: technitium
    network_mode: host
    environment:
      - DNS_SERVER_DOMAIN=pinas01.local
      - DNS_SERVER_ADMIN_PASSWORD=VMware123!
    volumes:
      - /mnt/data/technitium/config:/etc/dns
    restart: unless-stopped
