services:
  samba:
    image: dperson/samba:latest
    container_name: samba-server
    restart: unless-stopped
    volumes:
      - /mnt/data/files:/home/shared
    ports:
      - "139:139"
      - "445:445"
    command: -u "vmware;VMware1234" -s "files;/home/shared;yes;no;no;vmware"
